### PR TITLE
feat: add kafka reporter without cds

### PR DESCRIPTION
**Pull request by matianjun1**
add kafka reporter just like [SkyWalking Python Agent](https://github.com/apache/skywalking-python) implement

### CODE REVIEW

**Comment by arugal** [comment]
Hi @matianjun1 Please check the [test](https://github.com/SkyAPM/go2sky/pull/128/checks?check_run_id=3611470851) first , and I think a kafka-reporter E2E test should be added, using [skywalking-infra-e2e](https://github.com/apache/skywalking-infra-e2e).

**Comment by arugal** [comment]
The kafka-reporter dependence on [Shopify/sarama](github.com/Shopify/sarama), if submit code to [go2sky-plugins](https://github.com/SkyAPM/go2sky-plugins),  `go2sky` can still maintain less dependence, what do you think? @wu-sheng @matianjun1 @dmsolr

**Comment by wu-sheng** [comment]
Make sense to me. SkyWalking Kafka reporter for Java is in the reporter plugin list too.

**Comment by dmsolr** [comment]
Make sense.

**Comment by wu-sheng** [comment]
@matianjun1 Please follow the recommendation.

**Pull request closed without merging**
