### PR TITLE
fix: When serves both http&websocket,ws connection denied with "bad handshake".

### PR DESCRIPTION
**Pull request by nealwon**
When using package gorilla/websocket, calls Upgrader.Upgrade(w http.ResponseWriter, r *http.Request, responseHeader http.Header),it asserts the ResponseWriter to be a Hijacker implementation, if assertion fails ws connection will be denied.

Client error:  `websocket: bad handshake`
Server error:  `websocket: response does not implement http.Hijacker`

gorilla/websocket code details：server.go
```go
173   	h, ok := w.(http.Hijacker)
174   	if !ok {
175  		return u.returnError(w, r, http.StatusInternalServerError, "websocket: response does not implement http.Hijacker")
176  	}
```

### CODE REVIEW

**Comment by wu-sheng** [comment]
Please update the title and contents in English.

**Comment by arugal** [comment]
@nealwon I need to do another PR fix CI, please wait :)

**Comment by wu-sheng** [comment]
Could you share how this case happens?

gorilla/websocket seems a 3rd pary framework, rather than this one bundled with go core lib only.
If you plan to support this new library, you should land your codes to go2sky-plugins repository.

**Comment by nealwon** [comment]
Yes，it's a popular 3rd-part lib.
In my project, I use this lib(gorilla/websocket) and want to try to use skywalking as performance monitoring.When i load go2sky lib, service start up normally,but all clients cannot connect to server due to "bad handshake".
Non-core libs not supported by go2sky,I can use fork to test skywalking.

Now i'll close this PR!

**Comment by wu-sheng** [comment]
I mean this should be a plugin, not a core lib change.
You could create another client to inherit this and implement a new interface, which would be more nice.

**Comment by nealwon** [comment]
OK, thx.

**Pull request closed without merging**
