### PR TITLE
Adapter mosn

### PR DESCRIPTION
**Pull request by arugal**
Provide a least-dependent version of go2sky for [mosn](https://github.com/mosn/mosn/issues/1027).

### CODE REVIEW

**Comment by wu-sheng** [comment]
Set a different milestone for mosn release too.

**Comment by arugal** [comment]
FYI @taoyuanyuan @rootsongjc

**Comment by wu-sheng** [comment]
One question, the new milestone named as 0.4.0-mosn. AFAIK, there is no go2sky 0.4.0.

The go2sky-mosn release should be a fork release, especially for MOSN. We should keep the versioin as 0.3.0-mosn. The only change in the mosn branch should be grpc downgrade.

Please correct me if I am wrong.

**Comment by arugal** [comment]
> One question, the new milestone named as 0.4.0-mosn. AFAIK, there is no go2sky 0.4.0.
> The go2sky-mosn release should be a fork release, especially for MOSN. We should keep the versioin as 0.3.0-mosn. 

I will modify the milestone.

> The only change in the mosn branch should be grpc downgrade.

Let me try.

**Comment by wu-sheng** [comment]
> > The only change in the mosn branch should be grpc downgrade.
> Let me try.

It is fine if you need to release 0.4.0 on the master branch. My point is only, don't make too much change in the mosn branch. It will be. very hard to maintain.

**Comment by arugal** [comment]
@wu-sheng  I have reversed the extra changes, please review :)

**Pull request merged**
