### PR TITLE
fixed instance register without hostname and pid

### LINKED ISSUE #27: not work for go2sky.WithInstance(instanceName)
**Describe the bug**
Do reporter.NewGRPCReporter with the go2sky.TracerOption go2sky.WithInstance("instance@hostname")

but can not found the instance name "instance@hostname" at http://127.0.0.1:8080/trace on dropdown menu instance

**To Reproduce**
1. Install skywalking on windows 10
2. run /path/to/apache-skywalking-apm-bin/bin/startup.bat
3. type testtracer.go as follow:
package main

import (
	"context"
	"log"
	"time"

	"github.com/tetratelabs/go2sky"
	"github.com/tetratelabs/go2sky/reporter"
)

func main() {
	report, err := reporter.NewGRPCReporter("127.0.0.1:11800")
	if err != nil {
		log.Fatalf("new reporter error %v \n", err)
	}
	tracer, err := go2sky.NewTracer("serverName", go2sky.WithReporter(report), go2sky.WithInstance("instance@hostname"))
	if err != nil {
		log.Fatalf("create tracer error %v \n", err)
	}
	tracer.WaitUntilRegister()
	defer report.Close()

	span, ctx, err := tracer.CreateLocalSpan(context.Background())
	if err != nil {
		log.Fatalf("create new local span error %v \n", err)
	}
	span.SetOperationName("invoke data")
	span.Tag("kind", "outer")
	time.Sleep(time.Second)
	subSpan, _, err := tracer.CreateLocalSpan(ctx)
	if err != nil {
		log.Fatalf("create new sub local span error %v \n", err)
	}
	subSpan.SetOperationName("invoke inner")
	subSpan.Log(time.Now(), "inner", "this is right")
	time.Sleep(time.Second)
	subSpan.End()
	time.Sleep(500 * time.Millisecond)
	span.End()
	time.Sleep(time.Second)
}

go run testtracer.go
go2sky-gRPC2019/08/20 15:12:47 the id of service 'serverName' is 5
go2sky-gRPC2019/08/20 15:12:47 the id of instance 'instance@hostname' id is 6

4. access to http://127.0.0.1:8080/trace
 select the service "serverName", then click down instance, only 2 items over there: All and serverName

**Expected behavior**
I can found the instance "instance@hostname" at http://127.0.0.1:8080/trace in the dropdown menu "instance"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows]
 - Version [10]

**Additional context**

### PR DESCRIPTION
**Pull request by veily**
fixed #27

### CODE REVIEW

**Comment by wu-sheng** [comment]
CI fails, please fix it.

**Comment by veily** [comment]
image

**Comment by veily** [comment]
> CI fails, please fix it.

fixed.

**Comment by withlin** [comment]
Hi @veily  , and thanks for opening this pull request.

One comment about this patch:

 `hs, err := os.Hostname()` Why the err not return it?

**Pull request merged**
